# fly.toml app configuration file generated for implicit-computer on 2023-11-11T11:12:59-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "implicit-computer"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
